### ISSUE TITLE
Installation via winget

### ISSUE THREAD

**Issue by Bjego** [genotrance/px2#3]
Hey,
it would be great, if you could publish PX and PX2 via winget. 
This would make installing px much easier and winget is going to be the official packagemanager for Windows. And the publishing is YAML based, so it shouldn't be too complicated, I think.

https://docs.microsoft.com/en-us/windows/package-manager/package/repository

**Comment by Bananeweizen** [comment]
Given current usage of package managers, creating choco packages instead of winget would probably address more users.
